version: '3'
services:
  nginx:
    image: nginx
    restart: on-failure
    environment:
      - VIRTUAL_HOST=$VIRTUAL_HOST
      - LETSENCRYPT_HOST=$VIRTUAL_HOST
      - LETSENCRYPT_EMAIL=$LETSENCRYPT_EMAIL
    expose:
      - 80
    volumes:
      - ./public:/usr/share/nginx/html

  # 2022-11-4 https://github.com/nginx-proxy/nginx-proxy/issues/1204#issuecomment-549410286
  redirect:
    image: cusspvz/redirect
    restart: unless-stopped
    environment:
      VIRTUAL_HOST: "www.${VIRTUAL_HOST}"
      HTTPS_METHOD: noredirect
      LETSENCRYPT_HOST: "www.${VIRTUAL_HOST}"
      REDIRECT: "https://${VIRTUAL_HOST}"

networks:
  default:
    external:
      name: nginx-proxy
