version: '3'
services:
  nginx:
    image: nginx
    restart: on-failure
    environment:
      - VIRTUAL_HOST=bscc.dev
      - LETSENCRYPT_HOST=bscc.dev
      - LETSENCRYPT_EMAIL=daniel@example.com
    expose:
      - 80
    volumes:
      - ./public:/usr/share/nginx/html
networks:
  default:
    external:
      name: nginx-proxy
